### ISSUE TITLE
Upgrading from 1.2.1 to 1.3 RC

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz_installer_osx#5]
When I ran the 1.3RC installer on a Macbook running 10.11.6 (Yosemite), It created the /Applications/OpenToonz/OpenToonz stuff folder but overwrote the contents of /Applications/OpenToonz_1.2.app instead of installing a new /Applications/OpenToonz.app.

If you try to run OpenToonz_1.2.app expecting the old version to work, it throws an error.  If you rename OpenToonz_1.2.app to OpenToonz.app it will then start correctly.

NOTE: Originally when I first tried to install the 1.3RC, I had the OpenToonz_1.2.app installed someplace else for development reasons and it somehow detected that one and overwrote it!  I had to delete my other copy so it would install correctly under /Applications

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn , I'll look into it.

**Comment by shun-iwasawa** [comment]
Confirmed the problem.
OSX identifies the package with its identifier. According to the [manual page of pkgbuild](http://www.manpagez.com/man/1/pkgbuild/):

> **--identifier** pkg-identifier
> Specify a unique identifier for this package. The OS X Installer recognizes a package as being an upgrade to an already-installed package only if the package identifiers match, so it is advisable to set a meaningful, consistent identifier when you build the package.  pkgbuild will infer an identifier 
when building a package from a single component, but will fail otherwise if the identifier has not been set.

OT uses the same identifier `io.github.opentoonz` among versions. ([here](https://github.com/opentoonz/opentoonz_installer_osx/blob/master/app.rb#L28) in the script)
It seems to be the reason why the installer overwrites the application on the exiting ones.

I think a reasonable way to resolve this issue would be to uninstall the older versions of OT before installing V1.3 . For the future versions we plan to use the same name `OpenToonz.app` regardless of version number, so I think this kind of confusion will not occur.

I will add a notice to the download page for asking OSX users to uninstall the previous version before installing the new one.

**Comment by shun-iwasawa** [comment]
@manongjohn 
Instead of adding the notification, I decided to try altering the package identifier so that OSX will recognize V1.3RC as different package from older versions. I'll check if it works once the installer will be generated. Thanks!

**Comment by shun-iwasawa** [comment]
Unfortunately changing the package identifier did not work.
I'll add the notice this time.

------------
**UPDATE:**  I confirmed that the changing `CFBundleIdentifier` in the [BundleInfo.plist](https://github.com/opentoonz/opentoonz/blob/master/toonz/cmake/BundleInfo.plist.in#L13-L14) does separate the application and installs without overwriting. However, IMO it is not reasonable to easily change this value.

**Comment by manongjohn** [comment]
@shun-iwasawa I'm a little surprised no-one mentioned this before with prior upgrades when version number changed.  At any rate, I agree that the notice should be enough since we're moving to a version-less name now and we'd want the installer to upgrade/replace in the future.

Thanks for looking into it.

**Comment by manongjohn** [comment]
@shun-iwasawa  I just realized an issue with just a notice. You will need to have a notice on the download page from now on to uninstall older 1.2.1 or older versions. This notice will not help Morevna Edition or Linux Flat packs/Snap installs unless those maintainers add similar notices.

To avoid future issues when upgrading from much older versions to 1.3 or later, is it possible to rename the application file during install if the name of the app is not "OpenToonz.app"?  That will fix the problem.

Perhaps a rename of the stuff folder if an older one exists, just before overlaying updated/new contents with upgrade changes would also help frustrations with the upgrade.
